### ISSUE TITLE
[HOTFIX] 1.0

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#214]
**To be fixed**
- [x] #249
- [x] #255
- [x] #242
- [x] #247
- [x] #243
- [x] #257
- [x] #248
- [x] #250
- [x] #252
- [x] #251
- [x] #244
- [x] #245

**Branch**
214-hotfix-1.0

**Comment by AjobK** [comment]
Please add suggestions for hotfix 1.0 if any bugs or code smells are found

**Comment by jerohero** [comment]
Got into some trouble with 'On post creation the wrong author is shown'. I'm attempting to fetch the data from the user store, but this doesn't get updated while logging in or wherever. I could fetch it from the backend again (which doesn't seem efficient) with the username stored in profile store, but for some reason that still gives me Emily Washington, even though the actual username is stored properly. So I'm wondering whether fixing this thing I don't understand is also part of this issue?

**Comment by jerohero** [comment]
Hotfix suggestion: Website shows 404 error when no likes are found on a post

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/125174529-50c82400-e1c6-11eb-8203-c0c85b031bf2.png)

Made smiling face as profile picture. Color changes based on username hash.

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/125204833-6b120880-e27f-11eb-915f-703edb1106e0.png)

Fixed author display on post. Might want to change the default avatar_attachment

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/125210200-7c1e4200-e29e-11eb-89d7-d1300bb29b61.png)

Made sure commenting on new-post page is impossible. Before it was possible, making it so that literally any user creating a post could see the comment at the bottom of it

**Comment by AjobK** [comment]
For some reason I'm unable to reproduce #243 ? I'm quite sure there was a bug there, but maybe it fixed itself 🤯

**Comment by AjobK** [comment]
Fixed profile status by the way, which was broken because of an OO principe violation (updateProfile function).

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/127774596-1d05d9e9-852b-4b0d-84b6-8d4ac3e00843.png)

Made profile picture available and fixed menu items.

**Comment by jerohero** [comment]
Added new issue

**Comment by AjobK** [comment]
Closed because this is an old hotfix branch. Please create 1.1 for new hotfix items.
