### ISSUE TITLE
[240] Dockerize project

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#240]
**Current state**
The application requires specific steps of configuration for it to be able to run in development or production

**Expected state**
The application can be run locally or deployed to a droplet with a single command

**TO DO**
- [x] Write Dockerfile for frontend
- [x] Write Dockerfile for backend
- [x] Write docker-compose file

**Branch**
- 240-dockerise-project

**Comment by danielordaan** [comment]
Comment: 
For the image to run on Linux, the sass-loader version (and dependencies) had to be updated
It has not been tested whether this had any effect on running the code locally at this point
