### ISSUE TITLE
Be able to return the result from query #9

### ISSUE THREAD

**Issue by vQFire** [AjobK/Athena#28]
I have been working with the mysql. I can now select. But I can only console the result. That is not what I want obviously. So I need some help with that.  

So can you go to the branch `#9-backend-folder-structure` go to the file `select.js` it can be found in `src/controllers` and check out the file.

To see the outcome of the file do `node .\src\controllers\select` currently it does **NOT** work. To make it work you need to edit row 24 and edit it to everything except * . all or All. You also need to make sure you XAMMP is running MySQL and you have a database. That follows the following requirement:
```
Database: athena,
Table: User,
Row1: Whatever you want,
etc....
```

Please help me be able to return the result. For any question comment on this Issue or message me on dicord

**Comment by AjobK** [comment]
@vQFire Is this still relevant?

**Comment by vQFire** [comment]
No it is not....

**Comment by vQFire** [comment]
Because we are going to be using express this issue is not needed any more
