### ISSUE TITLE
[287] Updating post causes 404 error

### ISSUE THREAD

**Issue by jerohero** [AjobK/Athena#287]
**Current state**
Pressing the update button on your post while editing directs the user to /profile, giving a 404 error.

![image](https://user-images.githubusercontent.com/14930277/132121739-740f8158-e0ab-4766-980c-43575bf826c3.png)

**Expected state**
The update button should direct the user to the updated post, not /profile.

**TO DO**
- [ ] Direct user to updated post

**Necessities**
#0

**Comment by AjobK** [comment]
😢
