### ISSUE TITLE
[HOTFIX] 1.1

### ISSUE THREAD

**Issue by jerohero** [AjobK/Athena#288]
**To be fixed**
- [x] #285 
- [x] #287 
- [x] #295 
- [x] #310
- [x] #315
- [x] #318 

**Branch**
For each hotfix item a branch should be made. The branch name should be `<issue-number>-hotfix-<fitting name>`. Make sure to use the 'Hotfix' issue template.

**Comment by AjobK** [comment]
![image](https://user-images.githubusercontent.com/35965716/132124342-ffedcbf9-d653-4145-89da-b0d8c43497c2.png)

Redirect to post instead of homepage after creation works now!

**Comment by AjobK** [comment]
@jerohero Shouldn't we make a PR for this?

**Comment by AjobK** [comment]
Fixed isEmailTaken issue (Didn't properly check if email is taken at registration)

Changed seeded user e-mails from '<Name>@gmail.com' to lowercased '<name>@seaqull.com'

**Comment by AjobK** [comment]
Disallowed <name>@seaqull.com as e-mail for registration
