### ISSUE TITLE
[298] Profile Page Revamp V1 - Profile Card Revamp

### ISSUE THREAD

**Issue by MrGooss** [AjobK/Athena#298]
**Current state**
There is currently no profile card component for the profile page.

**Expected state**
There should be a profile card component that is visible on the profile page which is styled as in the designs on [Zeplin](Zeplin.io).

**TO DO**
- [x] Create profile card component
- [x] Style profile card component

**Branch**
298-profile-card-revamp

**Comment by AjobK** [comment]
@S-Goossens 

Ik heb je PR gecheckt. Je moet de followers nog vertonen als je op 'followers' klikt.

**Comment by MrGooss** [comment]
@AjobK Bestaat dat al? anders klinkt het als een andere issue
