### ISSUE TITLE
[313] Post Banner Attachment

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#313]
**Current state**
There is no way to add a post banner and/or crop it.

**Expected state**
The author of a post should be able to crop their post banner and also change it by uploading a file to our server. The foundation of this functionality has been made in #220.

**TO DO**
- [ ] Upload image (Drag 'n drop & clickable)
- [ ] Crop image

**Necessities**
#220

**Branch**
313-profile-banner-attachment

**Comment by jerohero** [comment]
Named the branch _313-post-banner-attachment_, assuming the named branch name was a typo.
