### ISSUE TITLE
Refactor snippets to components

### ISSUE THREAD

**Issue by Samvdg** [AjobK/Athena#32]
Hey guys,

I noticed that within the layouts (for example header) we were writing a lot of html while we shouldnt do that in the layout itself. I noticed in said header we had a nav with li elements while that could be made in a menu compenent for if we want to reusee it  again. or use it for entirely different pages. actually think smaller. the logo could also be an icon component too. the hamburger we load in in a component containing the entire nav etc etc. 

## What to do
- [x] make the header layout smaller by making more components
- [x] make a menu component
- [x] make an icon component
*etc*

## Updates
- made a new branch for picking apart the header
^ going to covert certain pieces of html code to components

**Comment by AjobK** [comment]
Please explain the current situation, and the expected situation.

Also, write these issues a shorter and more specific.

Is this a refactor job or an enhancement? Really confused with this one

**Comment by AjobK** [comment]
Finished issue
