### ISSUE TITLE
[347] Refactor Desktop Menu

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#347]
**Current state**
We use the old menu at the top

![image](https://user-images.githubusercontent.com/35965716/141470880-eb5c7702-380b-4fa0-a6b4-da783afb7a0d.png)

**Expected state**
We use the new menu according to design

**On a post**
![image](https://user-images.githubusercontent.com/35965716/141470854-96b544db-8b87-49e3-8c92-a65dfe9eb263.png)

**On homepage**
![image](https://user-images.githubusercontent.com/35965716/141470964-e00f9ba2-ab6e-4a08-836b-95107575b39f.png)

Search and filter don't work yet

**Necessities**
#0

**Branch**
347-refactor-desktop-menu

**Comment by JeroenVanVliet** [comment]
- [x]  User icon (arrow) will be changed to a hamburger menu, aligned on the right side of the navigation menu.
- [x] When open, there will be a full screen overlay. color given: #000000, 30% ish
- [ ] menu item width: 260-280px menu item padding (top/bottom): 10px
- [ ] menu dropdown, max-width: 300px. Include 20px gutter/ margin around menu items
- [ ] menu item margin (top/bottom): none
- [ ] menu dropdown: box-shadow: 0px, 10px, 16px rgba(#000000, 10%);

**Comment by AjobK** [comment]
**1. Current status**
Desktop and mobile navigation is done.
Desktop and mobile sub-navigation is pretty much done but needs some work.

**1.1 Desktop (sub)nav**
![image](https://user-images.githubusercontent.com/35965716/145105425-a1fe52f6-1c62-484b-a28b-6ee9baea75f7.png)

**1.2 Mobile (sub)nav**
![image](https://user-images.githubusercontent.com/35965716/145105635-3f78613b-4160-4632-8f83-cf600b4afb37.png)
  

**🔨 To fix**
- [x] Scrollbar should not be present on open subnav on mobile
- [ ] Bigger hitbox for subnav elements
- [x] Properly remove pointer events for mobile subnav. Currently it blocks clicking on elements when closed.  
  

**📝 Might do in another issue**
- [ ] Different open/close animation for mobile subnav  
  

**🚫 Will likely not do**
- [ ] Extra spacing for login, logout and register button (might discuss with @JeroenVanVliet )
