### ISSUE TITLE
[359] Post page revamp v1

### ISSUE THREAD

**Issue by jerohero** [AjobK/Athena#359]
**Current state**
The post page makes use of the old design.
![image](https://user-images.githubusercontent.com/14930277/145707643-47bc6a60-b46d-4850-aeee-c3dda2c6e31f.png)

**Expected state**
The post page should contain a first iteration in the new design (see Zeplin: Article-page - desktop - 2).
This issue does not include implementing/revamping description, rich styling and comment section.
![image](https://user-images.githubusercontent.com/14930277/145707783-86202e7f-267d-4c71-9ebe-60e28e70fb97.png)

-- NICE TO HAVE --
Read time and recency

**TO DO**
For the first iteration of this issue the following elements should be present:
- [x] Title
- [x] Banner image (including editing through a black overlay with pen icon, like with avatars)
- [x] Paragraphs content
- [ ] Responsiveness

Temporary implementations:
- [ ] Like button should at least be available (scroll along on left, thumb button on mobile)
- [ ] Author should at least be somewhere (doesn't matter where)

Nice to have features:
- [ ] Read time and recency

**Necessities**
#0

**Branch**
359-post-page-revamp-v1

**Comment by jerohero** [comment]
@JeroenVanVliet @AjobK I noticed the view count is not included in the designs, while it is already functional in the current state. Will this component be removed or was it just forgotten?

**Comment by AjobK** [comment]
@jerohero 

It was likely forgotten. Do not remove the feature. For now find a placeholder for the post views and pick this up on sunday with @JeroenVanVliet

**Comment by jerohero** [comment]
Also noticed there is no likes count

**Comment by AjobK** [comment]
> Also noticed there is no likes count

For this I also reference to my comment above. Sorry for the inconvenience. This should have been addressed prior to adding this issue to the sprint.

Take this up with @JeroenVanVliet. If further assistance is needed please say so
