### ISSUE TITLE
[370] Move Infinite Scrolling To New Backend

### ISSUE THREAD

**Issue by AjobK** [AjobK/Athena#370]
**Bug display and/or description**
Move to new back-end
#259 

**Reproduce**
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] Step ...

**Branch**
370-hotfix-move-infinite-scroll

**Comment by jerohero** [comment]
I went through the code that was added in the old backend, and it seems @AjobK already updated this last month in the new backend in the following commit: https://github.com/AjobK/Seaqull/commit/407eb9465be8b1c6872780702f9989b7df6eb369

So I think this issue can be closed?

**Comment by AjobK** [comment]
Has already been checked and it's in develop
