### ISSUE TITLE
[390] Avatar and username not showing on post creation page

### ISSUE THREAD

**Issue by jerohero** [AjobK/Athena#390]
**Bug display and/or description**
![image](https://user-images.githubusercontent.com/14930277/163712919-c1c32994-de21-4418-b41d-e6b05d22b3ab.png)
There was a fix for this issue before, but since this page was not merged back then this fix needs to be applied to this page as well.

**Reproduce**
- [ ] Step 1

**Branch**
390-hotfix-create-post-author-info

**Comment by jerohero** [comment]
Since the post page revamp has not been merged yet I added this commit to the post page revamp branch: #359

**Comment by AjobK** [comment]
Has been moved to #359
