### ISSUE TITLE
Popup Component

### ISSUE THREAD

**Issue by vQFire** [AjobK/Athena#42]
We need to create a popup component to show a popup on the screen.  
The popup needs the following component:

* - [ ]  Show overlay with color.
  * Default will follow the design
  * - [ ] Be able to pick own overlay color (transparent for example).
* - [ ] Create the popup content holder.
  * Will alway be centered (vertical and horizontal using flex)
  * - [ ] Be able to create and send your own content holder and overwrite the default.
  * - [ ] The popup holder should have a times icon (**X**).
  * - [ ] The holder should follow the register design
* - [ ] It should have a opening and closing function
  * - [ ] Be able to send a target class. When clicked it will open the popup.
  * - [ ] When you click on the times icon it should close the popup
  * - [ ] Close the popup when the overlay is clicked.
  * - [ ] Be able to open the popup after a certain time has passed

**Comment by AjobK** [comment]
Nice and specific
