### ISSUE TITLE
Frontend Routing

### ISSUE THREAD

**Issue by MiguelFieira** [AjobK/Athena#46]
**Current situation**
We have no way to navigate to other pages

**Expected situation**
We have a routing system for the front-end with which we can navigate through our website. This is done with [Next.JS](https://nextjs.org/learn/basics/getting-started/setup). The pages we can navigate to are 'home' and 'my profile'.

**Comment by AjobK** [comment]
Where are the description, labels and Milestone?

**Comment by AjobK** [comment]
Things still left to do

- [x] Fix error handling of Icon
- [x] Make component for items with <Link> wrapped around them

**Comment by AjobK** [comment]
Finished issue
